# Generated by Django 5.0.2 on 2024-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_rename_url_paper_arxiv_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='arxiv_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
